// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl9ioK5W_NiaVkgSDEMbZPFqOLeRmjJ-Y',
    appId: '1:577396855316:web:e95644374a02fb59cc8d01',
    messagingSenderId: '577396855316',
    projectId: 'rada-egerton',
    authDomain: 'rada-egerton.firebaseapp.com',
    storageBucket: 'rada-egerton.appspot.com',
    measurementId: 'G-1BZ3W547BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhptKtgTJG5abGcL-TT66uzk1QrVbEgB4',
    appId: '1:577396855316:android:476a481185abd3bccc8d01',
    messagingSenderId: '577396855316',
    projectId: 'rada-egerton',
    storageBucket: 'rada-egerton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3bn2k14HdGtMagt85vOmeOoRofxYyag',
    appId: '1:577396855316:ios:9699836ba73959edcc8d01',
    messagingSenderId: '577396855316',
    projectId: 'rada-egerton',
    storageBucket: 'rada-egerton.appspot.com',
    iosClientId: '577396855316-mi1pdg3tb8mlh5gtuepbce0jet04foi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.radaEgerton',
  );
}
